name: pubhub-notification

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  notification:
    name: notification
    runs-on: ubuntu-latest
    outputs:
      response: ${{steps.CloudSSO.response}}
    steps:
      - name: echo
        run: echo "Starting https request"
      - name: Request Postment Echo GET
        uses: fjogeleit/http-request-action@v1.5.0
        with:
          url: 'https://postman-echo.com/get'
          method: 'GET'
      - name: cloudsso
        uses: fjogeleit/http-request-action@v1.5.0
        id: ciscosso
        with:
          url: 'https://cloudsso.cisco.com/as/token.oauth2?grant_type=client_credentials&client_id=${{secrets.client_id}}&client_secret=${{secrets.client_secret}}'
          method: POST
      - name: echo
        run: echo ${{steps.cloudsso.response}}



           
  
     
