name: pubhub-notification

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  notification:
    name: notification
    runs-on: ubuntu-latest
    outputs:
      response: ${{steps.step1.response}}
    steps:
      - name: CloudSSO
        uses: fjogeleit/http-request-action@v1.5.0
          response: 
        with:
          url: 'https://cloudsso.cisco.com/as/token.oauth2?grant_type=client_credentials&client_id=${{secrets.client_id}}&client_secret=${{secrets.client_secret}}'
          method: POST



           
  




           
  
     
