name: pubhub-notification

on:
  push:
    branches:
      - main   # 👈 only run on main

jobs:
  notification:
    name: notification
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo "Starting https request"
      - name : PubHub API
        id: pubhub_request
        uses: fjogeleit/http-request-action@v1.5.0
        with:
          url: 'https://devnet.cisco.com/v1/pubhub/projects/sync/${{secrets.project_id}}/'
          timeout: 60000
          customHeaders: |
            {
              "Authorization": "Token ${{ secrets.pubhub_token }}"
            }
          method: GET
      - name: Debug response
        run: echo "${{ steps.pubhub_request.outputs.response }}"
